[package]
name = "templito"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gobble={path="../gobble/"}
anyhow = "1.0.31"
thiserror = "1.0.20"
